# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# LibFile: pysolidfive/tests/test_pysolidfive_render.py
#    Renders a representative sample of pysolidfive shapes with the *real* PythonSCAD binary and
#    compares them against committed golden images. Complements
#    pysolidfive/tests/test_pysolidfive.py (which checks SDF math against a numeric mock, never
#    touching a real binary) with an end-to-end check of actual meshing/rendering.
#
#    Every test here skips gracefully -- via self.skipTest(), not a failure -- when the real
#    render isn't available: no PythonSCAD binary installed, or no golden image committed yet.
#    Unlike the parent repo's own render tests (cap_box.py, sliding_box.py, ...), pysolidfive
#    itself has no bosl2/numpy dependency (see pysolidfive/__init__.py's module docstring), so
#    these tests aren't affected by the numpy hardened-runtime code-signing issue documented in
#    pysolidfive/tests/render_pysolidfive.py's module docstring -- that issue is specific to
#    bosl2 (and therefore to every *other* library's render tests), not to pysolidfive.
#
#    Golden images live in pysolidfive/tests/golden_images/ and are generated by
#    tests/generate_golden_images.py (run manually on a machine where rendering works).
#
# FileGroup: pysolidfive

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
# pysolidfive/tests/test_pysolidfive_render.py -> pysolidfive/tests -> pysolidfive -> repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from render_pysolidfive import (
    compare_images,
    find_pythonscad_binary,
    render_pysolidfive_shape,
)

GOLDEN_DIR = Path(__file__).resolve().parent / "golden_images"
OUT_DIR = Path(__file__).resolve().parent / "_render_output"

# Mean per-channel pixel difference (0-255 scale) below which two renders are considered a
# match. Loose enough to tolerate minor anti-aliasing/viewport differences across machines,
# tight enough to catch a genuinely wrong shape or a blank/error image.
_TOLERANCE = 12.0

# (test-name-suffix, pysolidfive expression) -- kept small and representative rather than exhaustive:
# one shape per distinct SDF technique documented in pysolidfive (corner masking, cyl edge masking,
# revolve masking, prismoid clamp, etc.), not one per public function.
SHAPES = [
    ("cuboid_rounded", "pysolidfive.cuboid([20.0, 20.0, 20.0], rounding=4)"),
    ("cuboid_chamfered", "pysolidfive.cuboid([20.0, 20.0, 20.0], chamfer=4)"),
    # edges="Z" rounds only the 4 vertical edges (not all 12) -- the per-axis-composition
    # fallback path in _cuboid_edge_sdf()/_rect2d() (see pysolidfive's module docstring), not the
    # exact-formula edges="ALL" fast path cuboid_rounded above exercises. Should come out with
    # crisp, flat top/bottom faces and rounded vertical corners -- a superellipse-profile
    # column, not the "ALL" case's pillow-like uniformly-rounded box.
    (
        "cuboid_rounded_partial_edges",
        "pysolidfive.cuboid([20.0, 20.0, 20.0], rounding=4, edges='Z')",
    ),
    ("sphere", "pysolidfive.sphere(r=10)"),
    ("cyl_rounded", "pysolidfive.cyl(h=20, r=8, rounding=2)"),
    ("torus", "pysolidfive.torus(major_radius=15, minor_radius=5)"),
    ("teardrop", "pysolidfive.teardrop(h=10, r=8)"),
    # A concave L-shaped outline (exact winding-number polygon SDF -- exercises concave-outline
    # sign correctness, which polygon_extrude()'s convex half-planes can't do), with a rounded
    # bottom rim and a flared top rim (both offset_sweep/os_circle-style end treatments).
    (
        "polygon_prism_concave_rims",
        "pysolidfive.polygon_prism([[0, 0], [40, 0], [40, 15], [15, 15], [15, 40], [0, 40]], "
        "h=12, rounding_bottom=2, rounding_top=-2)",
    ),
    # The named n-ary CSG combinators. union/difference/intersection are thin SDF min/max
    # composition (the operators |, &, - with list/varargs conventions); hull() is the
    # polyhedral support-plane construction -- two smooth children give the faceted-capsule
    # look on purpose (see hull()'s docstring), and the cuboid+point spike is exact.
    (
        "op_union",
        "pysolidfive.union(pysolidfive.cuboid([20.0, 20.0, 10.0], rounding=3, res=10), "
        "pysolidfive.sphere(r=8, res=10).translate([0.0, 0.0, 8.0]))",
    ),
    (
        "op_intersection",
        "pysolidfive.intersection(pysolidfive.cuboid([20.0, 20.0, 20.0], rounding=4, res=10), "
        "pysolidfive.sphere(r=12, res=10))",
    ),
    (
        "op_difference",
        "pysolidfive.difference(pysolidfive.cuboid([20.0, 20.0, 20.0], rounding=3, res=10), "
        "pysolidfive.zcyl(h=30, r=5, res=10), pysolidfive.xcyl(h=30, r=5, res=10))",
    ),
    (
        "op_hull_spheres",
        "pysolidfive.hull(pysolidfive.sphere(r=6, res=10), "
        "pysolidfive.sphere(r=6, res=10).translate([18.0, 0.0, 0.0]), directions=96)",
    ),
    (
        "op_hull_spike",
        "pysolidfive.hull(pysolidfive.cuboid([16.0, 16.0, 8.0], res=10), [[0.0, 0.0, 18.0]])",
    ),
]


class RealRenderTestCase(unittest.TestCase):
    binary: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.binary = find_pythonscad_binary()
        OUT_DIR.mkdir(exist_ok=True)

    def _render_and_compare(self, name: str, expr: str) -> None:
        if self.binary is None:
            self.skipTest("no real PythonSCAD binary found (set PYTHONSCAD_BIN to override)")

        golden = GOLDEN_DIR / f"{name}.png"
        out_png = OUT_DIR / f"{name}.png"

        result = render_pysolidfive_shape(expr, out_png)
        if not result.ok:
            self.skipTest(f"real render did not produce geometry, skipping: {result.error}")

        if not golden.is_file():
            self.skipTest(
                f"no golden image at {golden} yet -- run tests/generate_golden_images.py "
                "on a machine where rendering works"
            )

        assert result.image_path is not None
        diff = compare_images(golden, result.image_path)
        self.assertLessEqual(
            diff,
            _TOLERANCE,
            f"{name}: rendered image differs from golden by {diff:.2f} (tolerance {_TOLERANCE})",
        )

    def test_cuboid_rounded(self) -> None:
        self._render_and_compare(*SHAPES[0])

    def test_cuboid_chamfered(self) -> None:
        self._render_and_compare(*SHAPES[1])

    def test_cuboid_rounded_partial_edges(self) -> None:
        self._render_and_compare(*SHAPES[2])

    def test_sphere(self) -> None:
        self._render_and_compare(*SHAPES[3])

    def test_cyl_rounded(self) -> None:
        self._render_and_compare(*SHAPES[4])

    def test_torus(self) -> None:
        self._render_and_compare(*SHAPES[5])

    def test_teardrop(self) -> None:
        self._render_and_compare(*SHAPES[6])

    def test_polygon_prism_concave_rims(self) -> None:
        self._render_and_compare(*SHAPES[7])


if __name__ == "__main__":
    unittest.main()
