# Copyright (c) 2026, pinkfish
#
# Licensed under the BSD 2-Clause License. See the LICENSE file in the project
# root for the full license text.
# SPDX-License-Identifier: BSD-2-Clause

"""Hand-written documentation pages survive the docs build (SPEC DOC-1, DOC-6).

`docs/_rstgen.py` generates one stub per module and then sweeps away any `.rst` that does not
correspond to a module -- which is right for a stale stub and catastrophic for hand-written prose.
The sweep consults `_HANDWRITTEN_PAGES`, and a page missing from that set is **deleted on the next
build**, silently: removing a file raises no warning, and the generated `index.rst` simply stops
mentioning it. `docs/getting_started.rst` was written, committed, and gone by the next
`make -C docs html`, with a clean zero-warning build reporting success.

These tests make that failure loud, in the two directions it can go.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
RSTGEN = DOCS / "_rstgen.py"


def _allowlist() -> set[str]:
    """The `_HANDWRITTEN_PAGES` set, read from the generator's source."""
    body = RSTGEN.read_text().split("_HANDWRITTEN_PAGES = frozenset(", 1)[1].split(")", 1)[0]
    return set(re.findall(r'"([\w.]+)"', body))


def _module_stub_pages() -> set[str]:
    """Page names the sweep will keep because a module of that name exists.

    Mirrors `_cleanup_stale_stubs()`'s own rule -- ``name in _HANDWRITTEN_PAGES or name in known``,
    where *known* is the module set -- rather than guessing from a page's contents. A check that
    models the sweep differently from the sweep would pass while the sweep still deletes.
    """
    return {py.stem for py in (ROOT / "pybosl2").rglob("*.py") if not py.stem.startswith("_")}


def test_the_allowlist_is_readable() -> None:
    """A parse failure here would make every check below vacuously pass."""
    assert "index" in _allowlist(), "could not read _HANDWRITTEN_PAGES from _rstgen.py"


def test_no_hand_written_page_is_missing_from_the_allowlist() -> None:
    """A page the sweep does not recognise is deleted on the next build, without a warning."""
    at_risk = sorted(
        rst.stem
        for rst in DOCS.rglob("*.rst")
        if rst.parent.name != "specs" and rst.stem not in _allowlist() and rst.stem not in _module_stub_pages()
    )
    assert not at_risk, (
        "these pages are neither generated module stubs nor listed in `_HANDWRITTEN_PAGES`, so "
        f"`_cleanup_stale_stubs()` will delete them on the next docs build: {at_risk}. "
        "Add them to the allowlist in docs/_rstgen.py."
    )


def test_the_allowlist_has_no_stale_entries() -> None:
    """An entry for a page that no longer exists hides a deletion that already happened."""
    present = {rst.stem for rst in DOCS.rglob("*.rst")}
    stale = sorted(name for name in _allowlist() if name not in present)
    assert not stale, f"listed in _HANDWRITTEN_PAGES but no such page exists -- was it deleted? {stale}"


def test_the_front_door_exists_and_is_protected() -> None:
    """SPEC DOC-6: the docs open with a task-oriented page, and it has to survive a build."""
    page = DOCS / "getting_started.rst"
    assert page.exists(), "docs/getting_started.rst is the front door SPEC DOC-6 requires"
    assert "getting_started" in _allowlist(), (
        "the front door is not in `_HANDWRITTEN_PAGES`, so the next docs build deletes it"
    )


def test_the_generated_index_leads_with_the_front_door() -> None:
    """`index.rst` is generated, so the link must live in the generator, not in the file."""
    generator = RSTGEN.read_text()
    assert "getting_started" in generator, (
        "index.rst is generated by _rstgen.py -- a hand-added toctree entry is overwritten on the "
        "next build, which is what happened the first time (SPEC DOC-1)."
    )
    index = (DOCS / "index.rst").read_text()
    assert "getting_started" in index, "the generated index does not link the front door"


@pytest.mark.parametrize("step", ["Round its edges", "Cut a hole", "Measure it", "Save it"])
def test_the_front_door_carries_a_reader_end_to_end(step: str) -> None:
    """One worked part: build, round, cut, place, measure, save (SPEC DOC-6)."""
    assert step in (DOCS / "getting_started.rst").read_text(), f"the getting-started page lost its '{step}' step"


# --- the front door's non-rendered claims ---------------------------------------------------


def test_the_front_door_prose_examples_are_true() -> None:
    """The claims in the page's plain code blocks, which the general gate cannot see.

    `tests/test_example_claims.py` executes every `pythonscad-example` that claims a value and
    holds it to it -- which covers the four numbers in this page's walkthrough. The "where to go
    next" section uses plain ``::`` blocks instead, because they are illustrations rather than
    renderable steps, so its one claim is checked here.
    """
    from pybosl2.parts import Screw

    assert Screw("M6", length=20).pitch == pytest.approx(1.0), "the page claims `screw.pitch  # 1.0`"
