# Copyright (c) 2026, pinkfish
#
# Licensed under the BSD 2-Clause License. See the LICENSE file in the project
# root for the full license text.
# SPDX-License-Identifier: BSD-2-Clause

# Static type stub for the fluent turtle command methods.
#
# `_fluent.py` binds one method per turtle command with `setattr(TurtleCommands, ...)` from a
# single table, so the two turtles cannot drift from the command language (PLAN O-1b). That is
# invisible to a type checker, which made all 30 of them -- the whole fluent API -- unusable
# from typed code and unrenderable by any tool that walks the class. PLAN T-8 requires the
# stub; this is it, and `tests/test_turtle_stub.py` fails if the two drift apart.

from typing import Any, Self

__all__ = ["TurtleCommands"]

class TurtleCommands:
    def add_length(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def arc_down(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def arc_left(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def arc_left_to(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def arc_right(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def arc_right_to(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def arc_up(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def command(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def down(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def jump(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def left(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def move(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def right(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def roll(self, value: Any = ..., **kwargs: Any) -> Self: ...
    # `run` is not declared here: both concrete turtles override it with a real signature
    # (`run(commands, repeat=1)`), and that is what a caller sees.
    def scale_length(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def set_angle(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def set_arc_steps(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def set_direction(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def set_length(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def until_x(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def until_y(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def until_z(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def up(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def x_jump(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def x_move(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def y_jump(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def y_move(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def z_jump(self, value: Any = ..., **kwargs: Any) -> Self: ...
    def z_move(self, value: Any = ..., **kwargs: Any) -> Self: ...
