# Copyright (c) 2026, pinkfish
#
# Licensed under the BSD 2-Clause License. See the LICENSE file in the project
# root for the full license text.
# SPDX-License-Identifier: BSD-2-Clause

from collections.abc import Sequence
from typing import Any, Self

from pybosl2.color import Colorable
from pybosl2.distributors import Distributable

class _BaseShape(Colorable, Distributable):
    shape: Any
    size: Sequence[float] | None
    anchor: Any

    def _color_native(self, c: Any = None, alpha: float | None = None) -> Self: ...
    def _highlight_native(self) -> Self: ...
    def _ghost_native(self) -> Self: ...
    def _distribute(self, mats: list[Any]) -> list[Self]: ...  # type: ignore[override]
    def _wrap(self, new_shape: Any) -> Self: ...
    @staticmethod
    def _unwrap(x: object) -> Any: ...
    def bounds(self) -> tuple[list[float], list[float]]: ...
    def translate(self, v: Sequence[float]) -> Self: ...
    def move(self, v: Sequence[float]) -> Self: ...
    def rotate(self, *a: object, **k: object) -> Self: ...
    def rot(self, *a: object, **k: object) -> Self: ...
    def mirror(self, v: Sequence[float]) -> Self: ...
    def multmatrix(self, m: Sequence[Sequence[float]]) -> Self: ...
    def scale(self, v: float | Sequence[float]) -> Self: ...
    def right(self, x: float) -> Self: ...
    def left(self, x: float) -> Self: ...
    def back(self, y: float) -> Self: ...
    def forward(self, y: float) -> Self: ...
    def fwd(self, y: float) -> Self: ...
    def __or__(self, other: object) -> Self: ...
    def __and__(self, other: object) -> Self: ...
    def __sub__(self, other: object) -> Self: ...
    def __ror__(self, other: object) -> Self: ...
    def __rand__(self, other: object) -> Self: ...
    def __rsub__(self, other: object) -> Self: ...
    def __add__(self, other: Sequence[float]) -> Self: ...
    def __radd__(self, other: Sequence[float]) -> Self: ...
    def __mul__(self, other: float | Sequence[float]) -> Self: ...
    def __rmul__(self, other: float | Sequence[float]) -> Self: ...

    # Whitelisted native methods proxied via __getattr__
    def resize(self, new_size: float | Sequence[float]) -> Self: ...
    def render(self, convexity: int = 10) -> Self: ...
    def background(self) -> Self: ...
    def set_modifier(self, modifier: str) -> Self: ...
    def repair(self) -> Self: ...
    def wrap(self, radius: float, fn: int | None = None) -> Self: ...
    def pull(self, direction: Sequence[float], distance: float) -> Self: ...
    def oversample(self, sides: int) -> Self: ...
    def separate(self) -> list[Self]: ...
    def inside(self, point: Sequence[float]) -> bool: ...
    def convexity(self, convexity: int) -> Self: ...
    def fn(self, fn: int) -> Self: ...
    def fa(self, fa: float) -> Self: ...
    def fs(self, fs: float) -> Self: ...
    def roof(self) -> Self: ...
    def show(self) -> None: ...
