# Copyright (c) 2026, pinkfish
#
# Licensed under the BSD 2-Clause License. See the LICENSE file in the project
# root for the full license text.
# SPDX-License-Identifier: BSD-2-Clause

from collections.abc import Sequence
from typing import Any

from pybosl2._backend import (
    Solid as Solid,
)
from pybosl2._backend import (
    current_backend as current_backend,
)
from pybosl2._backend import (
    set_default_backend as set_default_backend,
)
from pybosl2._backend import (
    use_backend as use_backend,
)
from pybosl2._edges_lang import Anchor
from pybosl2.exceptions import (
    CrossBackendError as CrossBackendError,
)
from pybosl2.exceptions import (
    UnsupportedByBackendError as UnsupportedByBackendError,
)
from pybosl2.points import Point
from pybosl2.texture import TextureType

def cube(
    size: float | Sequence[float] = 1,
    center: bool | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
) -> Solid: ...
def cuboid(
    size: float | Sequence[float] = (1, 1, 1),
    p1: Point | None = None,
    p2: Point | None = None,
    chamfer: float | None = None,
    rounding: float | None = None,
    edges: Anchor | str | list[object] = "ALL",
    except_edges: list[Any] | None = None,
    trimcorners: bool = True,
    teardrop: bool | float = False,
    anchor: Anchor = ...,
    spin: float = 0,
    orient: Anchor = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def cyl(
    height: float | None = None,
    radius: float | None = None,
    center: bool | None = None,
    length: float | None = None,
    radius1: float | None = None,
    radius2: float | None = None,
    diameter: float | None = None,
    diameter1: float | None = None,
    diameter2: float | None = None,
    chamfer: float | None = None,
    chamfer1: float | None = None,
    chamfer2: float | None = None,
    rounding: float | None = None,
    rounding1: float | None = None,
    rounding2: float | None = None,
    circumscribe: bool = False,
    realign: bool = False,
    shift: Sequence[float] = (0, 0),
    anchor: Anchor | Sequence[float] | None = None,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
    chamfer_angle: float | None = None,
    chamfer_angle1: float | None = None,
    chamfer_angle2: float | None = None,
    from_end: bool = False,
    from_end1: bool | None = None,
    from_end2: bool | None = None,
    extra: float = 0.0,
    extra1: float | None = None,
    extra2: float | None = None,
    teardrop: float | bool = False,
    clip_angle: float = 90.0,
    texture: str | TextureType | None = None,
    tex_size: float | Sequence[float] | None = None,
    tex_reps: int | Sequence[int] | None = None,
    tex_depth: float = 1.0,
    tex_inset: float | bool = False,
) -> Solid: ...
def cylinder(
    height: float | None = None,
    radius1: float | None = None,
    radius2: float | None = None,
    center: bool | None = None,
    length: float | None = None,
    radius: float | None = None,
    diameter: float | None = None,
    diameter1: float | None = None,
    diameter2: float | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def octahedron(
    size: float = 1,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
) -> Solid: ...
def onion(
    radius: float | None = None,
    angle: float = 45,
    cap_height: float | None = None,
    circumscribe: bool = False,
    diameter: float | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def pie_slice(
    height: float | None = None,
    radius: float | None = None,
    angle: float = 30,
    center: bool | None = None,
    radius1: float | None = None,
    radius2: float | None = None,
    diameter: float | None = None,
    diameter1: float | None = None,
    diameter2: float | None = None,
    length: float | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def prismoid(
    size1: Sequence[float],
    size2: Sequence[float],
    height: float | None = None,
    shift: Sequence[float] = (0, 0),
    rounding: float | Sequence[float] = 0,
    rounding1: float | Sequence[float] | None = None,
    rounding2: float | Sequence[float] | None = None,
    chamfer: float | Sequence[float] = 0,
    chamfer1: float | Sequence[float] | None = None,
    chamfer2: float | Sequence[float] | None = None,
    length: float | None = None,
    center: bool | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def rect_tube(
    height: float | None = None,
    size: float | Sequence[float] | None = None,
    isize: float | Sequence[float] | None = None,
    center: bool | None = None,
    shift: Sequence[float] = (0, 0),
    wall: float | None = None,
    size1: float | Sequence[float] | None = None,
    size2: float | Sequence[float] | None = None,
    isize1: float | Sequence[float] | None = None,
    isize2: float | Sequence[float] | None = None,
    rounding: float | Sequence[float] = 0,
    rounding1: float | Sequence[float] | None = None,
    rounding2: float | Sequence[float] | None = None,
    inner_rounding: float | Sequence[float] = 0,
    inner_rounding1: float | Sequence[float] | None = None,
    inner_rounding2: float | Sequence[float] | None = None,
    chamfer: float | Sequence[float] = 0,
    chamfer1: float | Sequence[float] | None = None,
    chamfer2: float | Sequence[float] | None = None,
    inner_chamfer: float | Sequence[float] = 0,
    inner_chamfer1: float | Sequence[float] | None = None,
    inner_chamfer2: float | Sequence[float] | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    length: float | None = None,
) -> Solid: ...
def regular_prism(
    sides: int,
    height: float | None = None,
    radius: float | None = None,
    diameter: float | None = None,
    radius1: float | None = None,
    radius2: float | None = None,
    inner_radius: float | None = None,
    inner_diameter: float | None = None,
    side: float | None = None,
    length: float | None = None,
    chamfer: float | None = None,
    chamfer1: float | None = None,
    chamfer2: float | None = None,
    rounding: float | None = None,
    rounding1: float | None = None,
    rounding2: float | None = None,
    circumscribe: bool = False,
    realign: bool = False,
    shift: Sequence[float] = (0, 0),
    center: bool | None = None,
    anchor: Anchor | Sequence[float] | None = None,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def sphere(
    radius: float | None = None,
    diameter: float | None = None,
    circumscribe: bool = False,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def spheroid(
    radius: float | None = None,
    diameter: float | None = None,
    circumscribe: bool = False,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def teardrop(
    height: float | None = None,
    radius: float | None = None,
    angle: float = 45,
    cap_height: float | None = None,
    circumscribe: bool = False,
    radius1: float | None = None,
    radius2: float | None = None,
    diameter: float | None = None,
    diameter1: float | None = None,
    diameter2: float | None = None,
    cap_h1: float | None = None,
    cap_h2: float | None = None,
    chamfer: float = 0,
    chamfer1: float = 0,
    chamfer2: float = 0,
    realign: bool = False,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def torus(
    major_radius: float | None = None,
    minor_radius: float | None = None,
    center: bool | None = None,
    major_diameter: float | None = None,
    minor_diameter: float | None = None,
    outer_radius: float | None = None,
    inner_radius: float | None = None,
    outer_diameter: float | None = None,
    inner_diameter: float | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def tube(
    height: float | None = None,
    outer_radius: float | None = None,
    inner_radius: float | None = None,
    center: bool | None = None,
    outer_diameter: float | None = None,
    inner_diameter: float | None = None,
    wall: float | None = None,
    outer_radius1: float | None = None,
    outer_radius2: float | None = None,
    outer_diameter1: float | None = None,
    outer_diameter2: float | None = None,
    inner_radius1: float | None = None,
    inner_radius2: float | None = None,
    inner_diameter1: float | None = None,
    inner_diameter2: float | None = None,
    realign: bool = False,
    length: float | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
) -> Solid: ...
def wedge(
    size: Sequence[float] = (1, 1, 1),
    center: bool | None = None,
    anchor: Anchor | Sequence[float] = ...,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
) -> Solid: ...
def xcyl(
    height: float | None = None,
    radius: float | None = None,
    center: bool | None = None,
    length: float | None = None,
    radius1: float | None = None,
    radius2: float | None = None,
    diameter: float | None = None,
    diameter1: float | None = None,
    diameter2: float | None = None,
    chamfer: float | None = None,
    chamfer1: float | None = None,
    chamfer2: float | None = None,
    rounding: float | None = None,
    rounding1: float | None = None,
    rounding2: float | None = None,
    circumscribe: bool = False,
    realign: bool = False,
    shift: Sequence[float] = (0, 0),
    anchor: Anchor | Sequence[float] | None = None,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
    chamfer_angle: float | None = None,
    chamfer_angle1: float | None = None,
    chamfer_angle2: float | None = None,
    from_end: bool = False,
    from_end1: bool | None = None,
    from_end2: bool | None = None,
    extra: float = 0.0,
    extra1: float | None = None,
    extra2: float | None = None,
    teardrop: float | bool = False,
    clip_angle: float = 90.0,
    texture: str | TextureType | None = None,
    tex_size: float | Sequence[float] | None = None,
    tex_reps: int | Sequence[int] | None = None,
    tex_depth: float = 1.0,
    tex_inset: float | bool = False,
) -> Solid: ...
def ycyl(
    height: float | None = None,
    radius: float | None = None,
    center: bool | None = None,
    length: float | None = None,
    radius1: float | None = None,
    radius2: float | None = None,
    diameter: float | None = None,
    diameter1: float | None = None,
    diameter2: float | None = None,
    chamfer: float | None = None,
    chamfer1: float | None = None,
    chamfer2: float | None = None,
    rounding: float | None = None,
    rounding1: float | None = None,
    rounding2: float | None = None,
    circumscribe: bool = False,
    realign: bool = False,
    shift: Sequence[float] = (0, 0),
    anchor: Anchor | Sequence[float] | None = None,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
    chamfer_angle: float | None = None,
    chamfer_angle1: float | None = None,
    chamfer_angle2: float | None = None,
    from_end: bool = False,
    from_end1: bool | None = None,
    from_end2: bool | None = None,
    extra: float = 0.0,
    extra1: float | None = None,
    extra2: float | None = None,
    teardrop: float | bool = False,
    clip_angle: float = 90.0,
    texture: str | TextureType | None = None,
    tex_size: float | Sequence[float] | None = None,
    tex_reps: int | Sequence[int] | None = None,
    tex_depth: float = 1.0,
    tex_inset: float | bool = False,
) -> Solid: ...
def zcyl(
    height: float | None = None,
    radius: float | None = None,
    center: bool | None = None,
    length: float | None = None,
    radius1: float | None = None,
    radius2: float | None = None,
    diameter: float | None = None,
    diameter1: float | None = None,
    diameter2: float | None = None,
    chamfer: float | None = None,
    chamfer1: float | None = None,
    chamfer2: float | None = None,
    rounding: float | None = None,
    rounding1: float | None = None,
    rounding2: float | None = None,
    circumscribe: bool = False,
    realign: bool = False,
    shift: Sequence[float] = (0, 0),
    anchor: Anchor | Sequence[float] | None = None,
    spin: float = 0,
    orient: Anchor | Sequence[float] = ...,
    fn: int | None = None,
    fa: float | None = None,
    fs: float | None = None,
    chamfer_angle: float | None = None,
    chamfer_angle1: float | None = None,
    chamfer_angle2: float | None = None,
    from_end: bool = False,
    from_end1: bool | None = None,
    from_end2: bool | None = None,
    extra: float = 0.0,
    extra1: float | None = None,
    extra2: float | None = None,
    teardrop: float | bool = False,
    clip_angle: float = 90.0,
    texture: str | TextureType | None = None,
    tex_size: float | Sequence[float] | None = None,
    tex_reps: int | Sequence[int] | None = None,
    tex_depth: float = 1.0,
    tex_inset: float | bool = False,
) -> Solid: ...
def effective_defaults(shape: str, backend: str | None = ...) -> dict[str, Any]: ...
def polyhedron(points: Any, faces: Any = ..., **kwargs: Any) -> Solid: ...
def union(*solids: Solid) -> Solid: ...
def difference(*solids: Solid) -> Solid: ...
def intersection(*solids: Solid) -> Solid: ...
